version: '2'

services:
  app:
    image: php:8.2-fpm
    container_name: yii2_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    command: >
      bash -c "apt update &&
               apt install -y libzip-dev unzip curl libpng-dev libjpeg-dev libonig-dev libxml2-dev zip git &&
               docker-php-ext-install pdo pdo_mysql zip gd mbstring xml &&
               curl -sS https://getcomposer.org/installer | php &&
               mv composer.phar /usr/local/bin/composer &&
               composer install &&
               php-fpm"

  web:
    image: nginx:alpine
    container_name: yii2_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: yii2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
